config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users, only: %i[new create index]
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/oauth/callback', to: 'data#create_session'
  get '/index', to: 'data#index', as: :datas
  get '/shutdown', to: 'data#shutdown'
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 4 }
  validates :password, confirmation: true
  validates :email, uniqueness: true

  serialize :public_key

  def valid_signature?(encrypted_string)
    string_to_encrypt = self.email
    rsa_from_pub = OpenSSL::PKey::RSA.new self.public_key
    rsa_from_pub.public_decrypt(encrypted_string) == string_to_encrypt
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def check_shutdown
    logout if current_user && current_user.shutdown?
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  private

  def not_authenticated
    flash[:warning] = 'You have to authenticate to access this page.'
    redirect_to log_in_path
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :require_login, only: [:index]
  before_action :check_shutdown, only: [:index]
  before_action :authenticate_with_token, only: [:shutdown]

  def index
    oauth_provider_url = Rails.configuration.oauth_credentials['oauth_provider_url']

    @data = HTTParty.get "#{oauth_provider_url}/api/v1/users.json", {query: {access_token: current_user.current_access_token}}
  end

  def create_session
    oauth_token = Rails.configuration.oauth_credentials['oauth_token']
    oauth_secret = Rails.configuration.oauth_credentials['oauth_secret']
    oauth_redirect_uri = Rails.configuration.oauth_credentials['oauth_redirect_uri']
    oauth_provider_url = Rails.configuration.oauth_credentials['oauth_provider_url']
    public_key = Base64.urlsafe_decode64(params[:key])
    email = params[:email]

    if user = User.find_by(email: email)
      req_params = "client_id=#{oauth_token}&client_secret=#{oauth_secret}&code=#{params[:code]}&grant_type=authorization_code&redirect_uri=#{oauth_redirect_uri}"
      response = HTTParty.post("#{oauth_provider_url}/oauth/token", body: req_params)
      user.update_columns public_key: public_key, current_access_token: response['access_token']
      auto_login(user)

      redirect_to datas_path
    else
      redirect_to "#{oauth_provider_url}/oauth/authorize?client_id=#{oauth_token}&redirect_uri=#{oauth_redirect_uri}&response_type=code"
    end
  end

  def shutdown
    oauth_provider_url = Rails.configuration.oauth_credentials['oauth_provider_url']
    @user.update_attribute :shutdown, true
    redirect_to oauth_provider_url
  end

  protected
    def authenticate_with_token
      @user ||= User.find_by(current_access_token: params[:token])

      if @user && params[:signature].present?
        @user.valid_signature?(Base64.urlsafe_decode64(params[:signature]))
      else
        false
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < AuthenticationsController
  def new
  end

  def create
    if login(params[:email], params[:password])
      flash[:success] = 'Welcome back!'
      redirect_to root_path
    else
      flash.now[:warning] = 'E-mail and/or password is incorrect.'
      render 'new'
    end
  end

  def destroy
    logout

    flash[:success] = 'See you!'
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < AuthenticationsController
  before_action :require_login, only: [:index]
  before_action :check_shutdown

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)

      flash[:success] = 'Welcome!'

      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class flash
    if flash.key?(:success)
      'alert-success'
    elsif flash.key?(:warning)
      'alert-warning'
    end
  end

  def flash_body flash
    if flash.key?(:success)
      flash[:success]
    elsif flash.key?(:warning)
      flash[:warning]
    end
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/data/index.html.erb
<h1> Authorization Page / Display Page </h1>
<% if current_user.current_access_token %>
  <p> Here's the resource owner (user) </p>
  <%= @data[0]["email"] %>
  <p> <%= link_to 'Go back to Main App', Rails.configuration.oauth_credentials['oauth_provider_url'] %></p>
<% else %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oauth2ClientTestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <!-- Navigation links -->
      <div id="navbar" class="d-flex">
        <ul class="mr-auto nav">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to 'Sign Up', sign_up_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Log In', log_in_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
        <% if current_user %>
          <ul class="nav ml-auto">
            <li class="nav-item"><span class='nav-link'><%= current_user.name %></span></li>
            <li class="nav-item"><%= link_to 'Log Out', log_out_path, method: :delete, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>

      <!-- Alerts -->
      <div class="alert <%= flash_class(flash) %>" role="alert">
        <%= flash_body(flash) %>
      </div>

      <!-- Page contents -->
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1 class="text-center">All Users</h1>

app/views/users/new.html.erb
<h1 class="text-center">Registration</h1>

<%= form_for @user, html: {class: 'mx-auto w-50'} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
  </div>
  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>